-- Insert sample electronic archives with Algerian context
INSERT INTO public.electronic_archives (
  file_name,
  original_name,
  file_type,
  file_size,
  storage_path,
  document_category,
  tags,
  metadata,
  extracted_text,
  project_id,
  archived_by,
  status
) VALUES 
(
  'contrat_benali_20240115.pdf',
  'Contrat Travaux Publics - Ahmed Benali.pdf',
  'application/pdf',
  1250000,
  'archives/contrat_benali_20240115.pdf',
  'Contrat',
  ARRAY['urgent', 'travaux_publics', 'alger'],
  '{"client": "Ahmed Benali", "montant": "2500000 DZD", "duree": "6 mois", "localisation": "Alger Centre"}',
  'Contrat de travaux publics pour la rénovation d''un bâtiment administratif situé à Alger Centre. Montant: 2,500,000 DZD. Durée: 6 mois. Entrepreneur: Ahmed Benali.',
  1,
  'Fatima Khelifi',
  'active'
),
(
  'facture_cherif_20240220.pdf',
  'Facture N°2024-089 - Cherif Construction.pdf',
  'application/pdf',
  875000,
  'archives/facture_cherif_20240220.pdf',
  'Facture',
  ARRAY['paiement', 'construction', 'oran'],
  '{"numero": "2024-089", "montant": "1200000 DZD", "tva": "190000 DZD", "client": "Cherif Construction"}',
  'Facture N°2024-089 pour fourniture de matériaux de construction. Montant HT: 1,200,000 DZD. TVA: 190,000 DZD. Total TTC: 1,390,000 DZD.',
  2,
  'Omar Boumediene',
  'active'
),
(
  'plan_mosque_constantine.dwg',
  'Plans Architecturaux - Mosquée de Constantine.dwg',
  'application/octet-stream',
  5400000,
  'archives/plan_mosque_constantine.dwg',
  'Plan',
  ARRAY['architecture', 'mosquee', 'constantine', 'heritage'],
  '{"type": "plan_architectural", "surface": "800m2", "architecte": "Leila Mansouri", "ville": "Constantine"}',
  'Plans architecturaux pour la restauration de la mosquée historique de Constantine. Surface: 800m². Architecte: Leila Mansouri.',
  3,
  'Rachid Benaissa',
  'active'
),
(
  'rapport_hebdo_setif.pdf',
  'Rapport Hebdomadaire - Chantier Sétif.pdf',
  'application/pdf',
  750000,
  'archives/rapport_hebdo_setif.pdf',
  'Rapport',
  ARRAY['hebdomadaire', 'chantier', 'setif', 'avancement'],
  '{"semaine": "12", "avancement": "65%", "chef_chantier": "Karim Zeghdane", "effectif": "25 ouvriers"}',
  'Rapport hebdomadaire du chantier de Sétif. Semaine 12: Avancement 65%. Chef de chantier: Karim Zeghdane. Effectif: 25 ouvriers.',
  1,
  'Amina Hadji',
  'active'
),
(
  'correspondance_wilaya_blida.pdf',
  'Correspondance Officielle - Wilaya de Blida.pdf',
  'application/pdf',
  425000,
  'archives/correspondance_wilaya_blida.pdf',
  'Correspondance',
  ARRAY['officiel', 'wilaya', 'blida', 'autorisation'],
  '{"expediteur": "Wilaya de Blida", "objet": "Autorisation de construire", "reference": "WB/2024/156"}',
  'Correspondance officielle de la Wilaya de Blida concernant l''autorisation de construire N° WB/2024/156. Référence dossier administratif.',
  2,
  'Said Hamidi',
  'active'
),
(
  'photo_chantier_tlemcen.jpg',
  'Photos de Suivi - Chantier Tlemcen.jpg',
  'image/jpeg',
  3200000,
  'archives/photo_chantier_tlemcen.jpg',
  'Photo',
  ARRAY['suivi', 'chantier', 'tlemcen', 'photos'],
  '{"date_prise": "2024-03-15", "photographe": "Yacine Belhadi", "lieu": "Tlemcen", "phase": "gros_oeuvre"}',
  'Photos de suivi du chantier de Tlemcen prise le 15 mars 2024. Phase gros œuvre. Photographe: Yacine Belhadi.',
  3,
  'Nadia Bencheikh',
  'active'
),
(
  'certificat_qualite_annaba.pdf',
  'Certificat de Conformité - Laboratoire Annaba.pdf',
  'application/pdf',
  650000,
  'archives/certificat_qualite_annaba.pdf',
  'Certificat',
  ARRAY['qualite', 'laboratoire', 'annaba', 'conformite'],
  '{"laboratoire": "LCTP Annaba", "norme": "NA 442", "resultat": "Conforme", "technicien": "Djamel Berkane"}',
  'Certificat de conformité délivré par le LCTP d''Annaba selon la norme NA 442. Résultat: Conforme. Technicien: Djamel Berkane.',
  1,
  'Houria Zeghib',
  'active'
);