// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfxpuiudigfsfthifisl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmeHB1aXVkaWdmc2Z0aGlmaXNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjIyNDEsImV4cCI6MjA2NTczODI0MX0.suzKyl6CzM4vLLEx4Bg2mSjuKwheQb7XP-B-mpBWfeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);